-- ============================================================
-- Supabase PostgreSQL Schema for Smart AI Attendance System
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql
-- ============================================================

-- 1. Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    gender TEXT DEFAULT 'Other',
    major TEXT DEFAULT 'Computer Science',
    email TEXT,
    phone TEXT,
    class_name TEXT NOT NULL,
    photo_url TEXT,
    face_descriptor TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Phnom_Penh', NOW())
);

-- 2. Create Sessions Table
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_code TEXT,
    name TEXT NOT NULL,
    course_name TEXT NOT NULL,
    major TEXT DEFAULT 'Computer Science',
    lecturer TEXT DEFAULT 'Professor',
    room TEXT DEFAULT 'Room 101',
    class_name TEXT NOT NULL,
    session_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Phnom_Penh', NOW())
);

-- 3. Create Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    check_in_time TEXT NOT NULL,
    status TEXT DEFAULT 'PRESENT',
    check_in_method TEXT DEFAULT 'AI_FACE',
    confidence_score DOUBLE PRECISION DEFAULT 1.0,
    snapshot_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Phnom_Penh', NOW()),
    CONSTRAINT unique_student_session_date UNIQUE (student_id, session_id, date)
);

-- 4. Create System Logs Table
CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    details TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('Asia/Phnom_Penh', NOW())
);

-- 5. Seed a Default Active Session if table is empty
INSERT INTO public.sessions (session_code, name, course_name, major, lecturer, room, class_name, session_date, start_time, end_time, status)
SELECT 'CS-401-M', 'Morning Session - AI & Computer Vision', 'CS-401: Artificial Intelligence', 'Computer Science', 'Dr. Sokha', 'Room 304', 'Year4 S1', TO_CHAR(NOW() AT TIME ZONE 'Asia/Phnom_Penh', 'YYYY-MM-DD'), '08:00', '11:00', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM public.sessions);

-- 6. Setup Storage Bucket for Student Profile Photos & Snapshots (Publicly Accessible)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('attendance-media', 'attendance-media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Setup Storage Security Policies (Allow Public Read & Write for Media)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Public Access for attendance-media'
    ) THEN
        CREATE POLICY "Public Access for attendance-media"
        ON storage.objects FOR SELECT
        USING (bucket_id = 'attendance-media');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Allow Uploads for attendance-media'
    ) THEN
        CREATE POLICY "Allow Uploads for attendance-media"
        ON storage.objects FOR INSERT
        WITH CHECK (bucket_id = 'attendance-media');
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Allow Updates for attendance-media'
    ) THEN
        CREATE POLICY "Allow Updates for attendance-media"
        ON storage.objects FOR UPDATE
        USING (bucket_id = 'attendance-media');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'objects' AND policyname = 'Allow Deletes for attendance-media'
    ) THEN
        CREATE POLICY "Allow Deletes for attendance-media"
        ON storage.objects FOR DELETE
        USING (bucket_id = 'attendance-media');
    END IF;
END $$;
